### ISSUE TITLE
Infinite values in nonnegative cones?

### ISSUE THREAD

**Issue by stephane-caron** [oxfordcontrol/Clarabel.rs#14]
Would it be possible for Clarabel to handle $\pm\infty$ values in non-negative cones? (Alternatively the solver could provide a "big float" threshold above which it considers values are infinite.)

At present having an infinity values (e.g. ``np.inf`` in Python which maps to an IEEE 754 infinity) results in a numerical error.

Context: this issue arose from testing Clarabel on the ``QPTEST`` problem from the Maros-Meszaros test set.

## Reproduction steps

```python
import clarabel
import numpy as np
import scipy.sparse as spa

# This is not the full QPTEST problem, just the gist of the issue
P = spa.csc_matrix(np.array([[8.0, 2.0], [2.0, 10.0]]))
q = np.array([1.5, -2.0])
A = spa.eye(2, format="csc")
b = np.array([20.0, np.inf])

cones = [clarabel.NonnegativeConeT(2)]
settings = clarabel.DefaultSettings()
settings.verbose = True
solver = clarabel.DefaultSolver(P, q, A, b, cones, settings)
result = solver.solve()
print(f"{result.status}")
```

### Output

```
-------------------------------------------------------------
           Clarabel.rs v0.4.0  -  Clever Acronym              

                   (c) Paul Goulart                          
                University of Oxford, 2022                   
-------------------------------------------------------------

problem:
  variables     = 2
  constraints   = 2
  nnz(P)        = 3
  nnz(A)        = 2
  cones (total) = 1
    : Nonnegative = 1,  numel = 2

settings:
  linear algebra: direct / qdldl, precision: 64 bit
  max iter = 200, time limit = Inf,  max step = 0.990
  tol_feas = 1.0e-8, tol_gap_abs = 1.0e-8, tol_gap_rel = 1.0e-8,
  static reg : on, ϵ1 = 1.0e-8, ϵ2 = 4.9e-32
  dynamic reg: on, ϵ = 1.0e-13, δ = 2.0e-7
  iter refine: on, reltol = 1.0e-13, abstol = 1.0e-12,
               max iter = 10, stop ratio = 5.0
  equilibrate: on, min_scale = 1.0e-4, max_scale = 1.0e4
               max iter = 10

iter    pcost        dcost       gap       pres      dres      k/t        μ       step      
---------------------------------------------------------------------------------------------
  0       NaN       NaN     NaN     NaN     NaN  1.00e+00     NaN   ------   
  1       NaN       NaN     NaN     NaN     NaN  1.00e+00     NaN  0.00e+00  
---------------------------------------------------------------------------------------------
Terminated with status = NumericalError
solve time = 62.359µs
NumericalError
```

**Comment by goulart-paul** [comment]
Related to https://github.com/oxfordcontrol/Clarabel.jl/issues/85

Yes, we can do something like that.   We also had the related issue reported above (which I confess I had forgotten about).   I think the sticking point was that it was not clear to whether it was preferable to :

1) throw an error if given infinite bounds, so at least the solver fails more a bit more explanation, or 
2) internally convert Inf to some huge finite value as you suggest.    

For our own internal testing on the Maros set we used 5e19 as a proxy for Inf, which allowed us to solve all but 1 of the set (I think 7-8 were at reduced accuracy level).     The problem with this approach generally though it is that it's not really clear what number counts as "big" in general, i.e. you can see in the Maros set that some of the values have crazy scaling and produced optimal solutions with very large entries or optimal values.

That said, in OSQP we just set a limit value of [1e30](https://github.com/osqp/osqp/blob/e3e338ac26d7e5ff8c33fd95da275528ddca2e2a/include/constants.h#L99) and I don't think anybody has ever complained.    We could do something like that, and also make it settable perhaps.

Do you think one or the other of the above is preferable?

**Comment by stephane-caron** [comment]
From a user's perspective I would prefer option 2 with a parameter to override the default limit. Additionally, it could be nice to have a warning, e.g. if the input problem contains values larger than the default limit, nudging to the docs and inviting to set a custom limit for that problem. The goal would be to have a low barrier of entry for newcomers, who may blissfully use the solver and never run into this problem (I wasn't aware OSQP internally capped at ``1e30`` and I don't think I ever ran into it :sweat_smile:), with still some guidance when needed.

Option 1 actually provides even more guidance, but I guess it makes for more friction and a steeper barrier of entry for newcomers.

**Comment by goulart-paul** [comment]
OK, thank you for the input.   We are experimenting with different options to see what works.   It seems not entirely straightforward, since option 2 (and some variations thereof) when just applied directly can cause the solver to fail as well but in a different way.      We could just eliminate offending rows but that would make it much harder to dynamically set the bounds in situations where multiple solves are requested, or within some branch-and-bound scheme.

It seems that Gurobi also uses a big finite upper limit, also set to 1e30 [(link)](https://www.gurobi.com/documentation/9.5/refman/variables.html).   That might even be why that value was chosen in OSQP.

Also for clarification, since I had a look again at our Maros set testing.   What we were doing there was identifying rows with RHS values above 5e19 and manually removing then before even passing anything to the solver.    That's fine for our own testing, but I agree not something an end user should have to do.

**Comment by goulart-paul** [comment]
This is fixed in https://github.com/oxfordcontrol/Clarabel.rs/commit/b8315a09a8f55e72ec2c70615db063f5a317d369 and should be part of the next release version.

Inequality constraints with sufficiently large right hands (above 1e20 by default) are eliminated in a pre-solve step.   This limit is user configurable with a module level parameter if you prefer something different.

**Comment by goulart-paul** [comment]
Now in current release v0.4.1
