### ISSUE TITLE
Question: Will Clarabel support box cone?

### ISSUE THREAD

**Issue by lequant40** [oxfordcontrol/Clarabel.rs#25]
Hello there,

I am starting to benchmark Clarabel, and would like to know if support for box cone (to manage box constraints on variables more "natively" than with the positive cone) is something planned?

(Like SCS -> https://www.cvxgrp.org/scs/api/cones.html)

Cheers,

Roman

**Comment by goulart-paul** [comment]
We do not directly support interval (i.e. box) constraints.   The reason is that the "box cone" isn't really a cone, and it's generally harder to deal with that constraint directly in an interior point solver than it is in a projection-based first order solver like SCS or OSQP.     

I don't think it would make much difference to solve times anyway, since modelling such a constraint as a pair of one-sided bounds can be made about as a sparse as a single box constraint anyway.   Specifically, if you have a constraint like $\ell \le Ax \le u$ with some non-trivial $A$ matrix, then it would be better to remodel it as the set of constrants : 

  $$
\begin{aligned}
z &= Ax \\
  z &\le u \\
-z &\le -\ell \\
\end{aligned}
$$

rather than as :

  $$
\begin{aligned}
  Ax &\le u \\
-Ax &\le -\ell \\
\end{aligned}
$$

The reason being that in the second form you would have $A$ (possibly with many nonzeroes) appearing twice in the eventual linear system that is solved at every interior point iteration, whereas in the first case you would $A$ and then two additional block rows that only have a single entry each.   Given that we use a sparse linear solve internally those extra rows are unlikely to change the solve time by much.

**Comment by bodono** [comment]
> The reason is that the "box cone" isn't really a cone

Why isn't the box cone really a cone? I think it is a cone, but I agree that IPMs won't be able to use it effectively though.

**Comment by bodono** [comment]
Wait, this is specifically about the box _cone_, if you see in the link to the SCS docs shared above the definition of the box cone is:

<img width="381" alt="Screenshot 2023-04-14 at 14 17 05" src="https://user-images.githubusercontent.com/555071/232054303-be460cc3-f8f2-4ab9-b491-463b530efbb2.png">

it's not just the box, it's the perspective of the indicator of the box. The box cone combined with the constraint that $t=1$ yields the standard box. Having a cone is useful for use in the homogeneous embedding solvers and fast infeasibility certification. However, I'm not sure how an IPM could use the box cone without losing the main benefit that the projection solvers enjoy, which is moving badly conditioned data into the projection step, but it might be possible.

**Comment by bodono** [comment]
Makes sense, although now that I think about it perhaps IPMs _would_ be able to make use of the box cone. So maybe something to think about.
