### ISSUE TITLE
Convergence Difference Between Sedumi and Clarabel for Linear Problems

### ISSUE THREAD

**Issue by geoeo** [oxfordcontrol/Clarabel.rs#33]
Im running sedumi/clarabel for a linear optimization problem P = 0. Settings are as in the example i.e. equilibrate is enabled

Sedumi:
```
K.l = size(A,2); % Linear Cone equivalent to Clarabel NonNegative
pars.eps = 1e-8;
pars.maxiter = 1000;
pars.theta = 0.25;
pars.beta = 0.5;
[X,Y,info] = sedumi(A,B,C,K,pars);



SeDuMi 1.3.7 by AdvOL, 2005-2008 and Jos F. Sturm, 1998-2003.
Alg = 2: xz-corrector, Adaptive Step-Differentiation, theta = 0.250, beta = 0.500
eqs m = 2328, order n = 3721, dim = 3721, blocks = 1
nnz(A) = 8060 + 0, nnz(ADA) = 13799, nnz(L) = 8064
 it :     b*y       gap    delta  rate   t/tP*  t/tD*   feas cg cg  prec
  0 :            5.16E+03 0.000
  1 :  -9.23E+03 2.83E+03 0.000 0.5492 0.9000 0.9000   4.33  1  1  4.1E+01
  2 :  -8.81E+02 8.64E+02 0.000 0.3051 0.9000 0.9000   2.57  1  1  8.2E+00
  3 :   1.11E+02 7.55E+01 0.000 0.0874 0.9900 0.9900   1.29  1  1  8.5E-01
  4 :  -4.18E-01 5.54E+00 0.000 0.0733 0.9900 0.9900   1.02  1  1  4.0E-01
  5 :  -1.50E+01 5.29E-01 0.000 0.0956 0.9900 0.9900   1.00  1  1  5.4E-02
  6 :  -1.55E+01 1.18E-05 0.000 0.0000 0.9999 0.9999   1.00  1  1
iter seconds digits       c*x               b*y
  6      0.0  14.0 -1.5500000000e+01 -1.5500000000e+01
|Ax-b| =   1.0e-11, [Ay-c]_+ =   1.3E-16, |x|=  3.9e+01, |y|=  1.7e+04

Detailed timing (sec)
   Pre          IPM          Post
1.422E-01    4.195E-02    1.509E-03
Max-norms: ||b||=1, ||c|| = 100,
Cholesky |add|=0, |skip| = 3, ||L.L|| = 2.53566.
```

Clarabel:
```
-------------------------------------------------------------
           Clarabel.rs v0.5.0  -  Clever Acronym              

                   (c) Paul Goulart                          
                University of Oxford, 2022                   
-------------------------------------------------------------

problem:
  variables     = 3720
  constraints   = 2328
  nnz(P)        = 0
  nnz(A)        = 8660160
  cones (total) = 1
    : Nonnegative = 1,  numel = 2328

settings:
  linear algebra: direct / qdldl, precision: 64 bit
  max iter = 50, time limit = Inf,  max step = 0.990
  tol_feas = 1.0e-8, tol_gap_abs = 1.0e-8, tol_gap_rel = 1.0e-8,
  static reg : on, ϵ1 = 1.0e-8, ϵ2 = 4.9e-32
  dynamic reg: on, ϵ = 1.0e-13, δ = 2.0e-7
  iter refine: on, reltol = 1.0e-13, abstol = 1.0e-12,
               max iter = 10, stop ratio = 5.0
  equilibrate: on, min_scale = 1.0e-4, max_scale = 1.0e4
               max iter = 10

iter    pcost        dcost       gap       pres      dres      k/t        μ       step      
---------------------------------------------------------------------------------------------
  0  +1.5933e+04  +1.3028e+06  8.08e+01  6.27e-01  2.29e+00  1.00e+00  7.14e+02   ------   
  1  +1.5803e+04  +1.3028e+06  8.14e+01  8.54e-02  2.16e+00  1.30e+02  7.06e+02  1.91e-01  
  2  +1.5748e+04  +1.3028e+06  8.17e+01  3.81e-02  2.03e+00  1.85e+02  7.01e+02  9.74e-02  
  3  +1.5650e+04  +1.3028e+06  8.22e+01  8.29e-02  1.98e+00  2.83e+02  6.45e+02  2.19e-01  
  4  +1.5390e+04  +1.3028e+06  8.37e+01  2.02e-02  1.81e+00  5.43e+02  5.40e+02  5.01e-01  
  5  +1.4692e+04  +1.3028e+06  8.77e+01  9.36e-03  2.29e+00  1.24e+03  2.90e+02  7.72e-01  
  6  +8.8915e+03  +1.3028e+06  1.46e+02  4.08e-03  1.68e+00  7.04e+03  5.50e+01  9.90e-01  
  7  -5.8897e+05  +1.3028e+06  3.21e+00  4.67e-05  7.57e-02  6.05e+05  6.40e-01  9.89e-01  
  8  -6.0478e+07  +1.3028e+06  4.74e+01  4.67e-07  7.58e-04  6.05e+07  6.40e-03  9.90e-01  
  9  -6.0494e+09  +1.3028e+06  4.64e+03  4.67e-09  7.58e-06  6.05e+09  6.40e-05  9.90e-01  
---------------------------------------------------------------------------------------------
Terminated with status = PrimalInfeasible
solve time = 151.522276563s
The application panicked (crashed).
Message:  capacity overflow
Location: library/alloc/src/raw_vec.rs:525
```
 The only potential issue I might have is converting sparse nalgebra matricies to clarabel. But currently there is no way to probe the CSC matrices. Where A is a DMatrix and B and C are DVectors.  Changing type to f32 doesnt help getting Nans

For reference:

```
    let B_vec = B.iter().map(|v| *v).collect::<Vec<_>>();
    let C_vec = C.iter().map(|v| *v).collect::<Vec<_>>();

    let mut A_coo_na = nalgebra_sparse::CooMatrix::<Float>::new(A.nrows(),A.ncols());
    for r in 0..A.nrows() {
        for c in 0..A.ncols() {
            A_coo_na.push(r,c,A[(r,c)]);
        }
    }
    let A_csc_na = nalgebra_sparse::CscMatrix::<Float>::from(&A_coo_na);

    let A_scs_clarabel = clarabel::algebra::CscMatrix::<Float>::new(
        A.nrows(),
        A.ncols(),
        A_csc_na.col_offsets().to_vec(),
        A_csc_na.row_indices().to_vec(),
        A_csc_na.values().to_vec()
    );

    let cones = [clarabel::solver::NonnegativeConeT::<Float>(A.nrows())];
    let P_cl = clarabel::algebra::CscMatrix::<Float>::spalloc(C.nrows(), C.nrows(), 0);

    (P_cl, A_scs_clarabel,B_vec,C_vec,cones)
```

**Comment by goulart-paul** [comment]
It looks like two separate (probably related) problems there.   The first is that the reported number of nonzeros for A is huge : `nnz(A)  = 8660160` in clarabel, while only `nnz(A) = 8060 + 0` in Sedumi.    Probably something has gone wrong with the conversion of `A` somehow, thought I don't immediately see what it is.

You could try adding a check on the formatting of your input matrix like this:
```
assert!(A.check_format().is_ok());
```
and see if that throws an error or not.

The second is the panic once the solver terminated.   I don't understand since I don't think there should even be any memory allocation going on once the solver hits that point in the code.    Maybe try running with `RUST_BACKTRACE=1` and post what you get. 

Changing to f32 isn't going to help here since I think your problem has been mangled somehow before it even hits the solver.

Are you able to provide an MWE that reproduces this error for us to investigate?

**Comment by goulart-paul** [comment]
One other possibility : is your original `A` matrix some dense object with lots of zeros in it?    This bit of code:
```
  for r in 0..A.nrows() {
        for c in 0..A.ncols() {
            A_coo_na.push(r,c,A[(r,c)]);
        }
```
is not testing for zero entries before the `push`.   The result is that you are passing a matrix in sparse format, but with many zero entries since `nalgebra_sparse::CscMatrix::<Float>::from(&A_coo_na)` seemingly doesn't squeeze out any zeros in the conversion.   

Note 3720*2328 = 86601060, so it looks from the clarabel output that your sparse A matrix has an entry in every one of its entries.

**Comment by geoeo** [comment]
I tried checking the contents of both sparse matrices. But I couldnt see a rekevant method. Is there a way to probe specific row,column elements for a clarabel csc matrix?

**Comment by goulart-paul** [comment]
There is only 

```assert!(A_scs_clarabel.check_format().is_ok())```

which checks that the matrix is properly formatted, i.e. internally compatible dimensions, row values monotonically increasing in each column, no row values out of bounds etc.   If that passes then the matrix is formatted correctly (barring some bug in the `check_format` method itself of course....)

There is no function at present that allows for direct indexing, i.e. something like `A_scs_clarabel[(row,col)]`, because we never do anything like that internally.   It would be easy enough to add as a user-facing utility though if you think it would be useful.

Are you certain that the panic is coming from the solver itself?   It is reporting the solve time, so it has reached the bit of the code that outputs final results and timing here: https://github.com/oxfordcontrol/Clarabel.rs/blob/26d938107f3f2aa61756573a1a73fcfde95d53ac/src/solver/implementations/default/info_print.rs#L114

That function is itself only called as the solver is about to exit, i.e. from here: https://github.com/oxfordcontrol/Clarabel.rs/blob/26d938107f3f2aa61756573a1a73fcfde95d53ac/src/solver/core/solver.rs#L363

I therefore don't understand the source of the panic.    Did you try with `RUST_BACKTRACE=1`?

**Comment by geoeo** [comment]
No your right: The panic is from some other code which I had to change to satisfy return statements with clarabel. So disregard this. But it still terminates with `Terminated with status = PrimalInfeasible`.

Regarding the CSCMatrix, for me it would be helpful, because I can never really check if my original matrix has been converted successfully / I made a mistake with parsing.

**Comment by goulart-paul** [comment]
Direct CSC data lookup implemented on [this](
https://github.com/oxfordcontrol/Clarabel.rs/tree/pg/csc_direct_indexing) branch.   I didn't make it a PR since I will fold that into a slightly more general upgrade of our examples and unit testing code.

Doing something like:
```
A.get_entry((row, col))
```
will return an `Option<f64>`, assuming you are passing `f64` data.  The option contains the value at that `(row,col)` position (NB: zero-indexed) if it is a structural nonzero of the sparse matrix.   Otherwise `None`.

**Comment by geoeo** [comment]
Thanks a lot.

**Comment by geoeo** [comment]
So I checked the matrices and they seem to be equal. However I also checked the Sedumi documentation and it seems the cone e.g is the dual space but in clarabel it is in the primal space. So I not sure if im mapping this problem correctly. Thanks for your help, feel free to close this issue.

**Comment by goulart-paul** [comment]
OK, will close for now.   Two suggestions though:

If your problem is an LP then the cone you are using (i.e. the nonnegative orthant) is the dual of itself.   This suggests that the use of primal vs dual cone is probably not your issue here.

This solver comes with a python interface.   You might find it easier to do your testing with the solver rusing python + cvxpy, since that will handle conversion to the solver's required format for you.   You could also test against other solvers to see if the problem is a modelling issue or a solver one.

**Comment by geoeo** [comment]
Interestingly it work in cvxpy with clarabel

```
x = cp.Variable(cols,pos=True)
prob = cp.Problem(cp.Minimize(C.T@x),
                 [A @ x == B])

#s = "ECOS"
s = "CLARABEL"

prob.solve(solver=s,verbose=True)
```

```
problem:
  variables     = 3720
  constraints   = 6048
  nnz(P)        = 0
  nnz(A)        = 11780
  cones (total) = 2
    :        Zero = 1,  numel = 2328
    : Nonnegative = 1,  numel = 3720

settings:
  linear algebra: direct / qdldl, precision: 64 bit
  max iter = 200, time limit = Inf,  max step = 0.990
  tol_feas = 1.0e-8, tol_gap_abs = 1.0e-8, tol_gap_rel = 1.0e-8,
  static reg : on, ϵ1 = 1.0e-8, ϵ2 = 4.9e-32
  dynamic reg: on, ϵ = 1.0e-13, δ = 2.0e-7
  iter refine: on, reltol = 1.0e-13, abstol = 1.0e-12,
               max iter = 10, stop ratio = 5.0
  equilibrate: on, min_scale = 1.0e-4, max_scale = 1.0e4
               max iter = 10

iter    pcost        dcost       gap       pres      dres      k/t        μ       step      
---------------------------------------------------------------------------------------------
  0  +1.5932e+04  +1.5932e+04  5.39e-13  4.20e-01  2.26e-01  1.00e+00  7.31e+01   ------   
  1  -1.4493e+03  -1.4458e+03  2.41e-03  5.13e-02  2.44e-02  3.60e+00  1.40e+01  8.90e-01  
  2  +2.2851e+02  +2.2923e+02  3.16e-03  1.12e-02  2.53e-03  7.41e-01  2.70e+00  9.01e-01  
  3  +1.2151e+01  +1.2185e+01  2.81e-03  6.11e-04  1.26e-04  3.51e-02  1.46e-01  9.49e-01  
  4  -1.3758e+01  -1.3753e+01  3.20e-04  7.95e-05  1.68e-05  4.53e-03  1.96e-02  9.30e-01  
  5  -1.5482e+01  -1.5482e+01  2.93e-06  8.19e-07  1.73e-07  4.67e-05  2.03e-04  9.90e-01  
  6  -1.5500e+01  -1.5500e+01  2.93e-08  8.20e-09  1.73e-09  4.67e-07  2.03e-06  9.90e-01  
  7  -1.5500e+01  -1.5500e+01  2.93e-10  8.20e-11  1.73e-11  4.67e-09  2.03e-08  9.90e-01  
---------------------------------------------------------------------------------------------
Terminated with status = Solved
solve time = 13.504548ms
-------------------------------------------------------------------------------
                                    Summary                                    
-------------------------------------------------------------------------------
(CVXPY) May 07 02:14:34 AM: Problem status: optimal
(CVXPY) May 07 02:14:34 AM: Optimal value: -1.550e+01
(CVXPY) May 07 02:14:34 AM: Compilation took 7.495e-02 seconds
(CVXPY) May 07 02:14:34 AM: Solver (including time spent in interface) took 1.913e-02 seconds
```

Rust:
```
problem:
  variables     = 3720
  constraints   = 2328
  nnz(P)        = 0
  nnz(A)        = 8060
  cones (total) = 1
    : Nonnegative = 1,  numel = 2328

settings:
  linear algebra: direct / qdldl, precision: 64 bit
  max iter = 100, time limit = Inf,  max step = 0.990
  tol_feas = 1.0e-8, tol_gap_abs = 1.0e-8, tol_gap_rel = 1.0e-8,
  static reg : on, ϵ1 = 1.0e-8, ϵ2 = 4.9e-32
  dynamic reg: on, ϵ = 1.0e-13, δ = 2.0e-7
  iter refine: on, reltol = 1.0e-13, abstol = 1.0e-12,
               max iter = 10, stop ratio = 5.0
  equilibrate: on, min_scale = 1.0e-4, max_scale = 1.0e4
               max iter = 10

iter    pcost        dcost       gap       pres      dres      k/t        μ       step      
---------------------------------------------------------------------------------------------
  0  +1.5933e+04  +1.3028e+06  8.08e+01  6.27e-01  2.29e+00  1.00e+00  7.14e+02   ------   
  1  +1.5803e+04  +1.3028e+06  8.14e+01  8.54e-02  2.16e+00  1.30e+02  7.06e+02  1.91e-01  
  2  +1.5748e+04  +1.3028e+06  8.17e+01  3.81e-02  2.03e+00  1.85e+02  7.01e+02  9.74e-02  
  3  +1.5650e+04  +1.3028e+06  8.22e+01  8.29e-02  1.98e+00  2.83e+02  6.45e+02  2.19e-01  
  4  +1.5390e+04  +1.3028e+06  8.37e+01  2.02e-02  1.81e+00  5.43e+02  5.40e+02  5.01e-01  
  5  +1.4690e+04  +1.3028e+06  8.77e+01  9.36e-03  2.29e+00  1.24e+03  2.90e+02  7.72e-01  
  6  +8.8977e+03  +1.3028e+06  1.45e+02  4.08e-03  1.68e+00  7.04e+03  5.50e+01  9.90e-01  
  7  -5.8890e+05  +1.3028e+06  3.21e+00  4.67e-05  7.57e-02  6.05e+05  6.40e-01  9.89e-01  
  8  -6.0478e+07  +1.3028e+06  4.74e+01  4.67e-07  7.58e-04  6.05e+07  6.40e-03  9.90e-01  
  9  -6.0493e+09  +1.3028e+06  4.64e+03  4.67e-09  7.58e-06  6.05e+09  6.40e-05  9.90e-01  
---------------------------------------------------------------------------------------------
Terminated with status = PrimalInfeasible
solve time = 8.200614ms
``` 

A couple of things are interesting:

1) The nnz count of A in the python version is higher at 11780 vs 8060 in Rust. H
However I "counted" the nnz values I push into A and they are indeed 8060. So I seems cvx augments the problem somehow?
2) The cvx version implicitly includes zero constraints. In both version I only use non-negative constraints on the *x* vector.

**Comment by goulart-paul** [comment]
The output from the CVXPY version says that you have 3720 linear inequalities (the Nonnegative cone part) and 2328 equalities (the Zero cone part).   The solver output and your python code indicate that your contraints are modelled as $Ax = b, \quad x\ge 0$.   Note that the "A" matrix as far as the solver is concerned is then `[A; I]`.

In the Rust one version it looks like you instead have a model that only has constraints $Ax \le b$ based on the cone descriptions and the difference in the number of nonzeros in A.   Note that the Python version has 3720 extra nonzeros in `A` relative to the Rust one, which is exactly the same as the number of nonzeros in the `I` appearing above.

**Comment by geoeo** [comment]
Yes A_cvx is `[A;I]` and b_cxv is `[b;0s]. So I augmented the matrices in Rust and now it converges.

```
-------------------------------------------------------------
           Clarabel.rs v0.5.0  -  Clever Acronym              

                   (c) Paul Goulart                          
                University of Oxford, 2022                   
-------------------------------------------------------------

problem:
  variables     = 3720
  constraints   = 6048
  nnz(P)        = 0
  nnz(A)        = 11780
  cones (total) = 2
    :        Zero = 1,  numel = 2328
    : Nonnegative = 1,  numel = 3720

settings:
  linear algebra: direct / qdldl, precision: 64 bit
  max iter = 100, time limit = Inf,  max step = 0.990
  tol_feas = 1.0e-8, tol_gap_abs = 1.0e-8, tol_gap_rel = 1.0e-8,
  static reg : on, ϵ1 = 1.0e-8, ϵ2 = 4.9e-32
  dynamic reg: on, ϵ = 1.0e-13, δ = 2.0e-7
  iter refine: on, reltol = 1.0e-13, abstol = 1.0e-12,
               max iter = 10, stop ratio = 5.0
  equilibrate: on, min_scale = 1.0e-4, max_scale = 1.0e4
               max iter = 10

iter    pcost        dcost       gap       pres      dres      k/t        μ       step      
---------------------------------------------------------------------------------------------
  0  +1.5932e+04  +1.5932e+04  5.39e-13  4.20e-01  2.26e-01  1.00e+00  7.31e+01   ------   
  1  -1.4493e+03  -1.4458e+03  2.41e-03  5.13e-02  2.44e-02  3.60e+00  1.40e+01  8.90e-01  
  2  +2.2851e+02  +2.2923e+02  3.16e-03  1.12e-02  2.53e-03  7.41e-01  2.70e+00  9.01e-01  
  3  +1.2151e+01  +1.2185e+01  2.81e-03  6.11e-04  1.26e-04  3.51e-02  1.46e-01  9.49e-01  
  4  -1.3758e+01  -1.3753e+01  3.20e-04  7.95e-05  1.68e-05  4.53e-03  1.96e-02  9.30e-01  
  5  -1.5482e+01  -1.5482e+01  2.93e-06  8.19e-07  1.73e-07  4.67e-05  2.03e-04  9.90e-01  
  6  -1.5500e+01  -1.5500e+01  2.93e-08  8.20e-09  1.73e-09  4.67e-07  2.03e-06  9.90e-01  
  7  -1.5500e+01  -1.5500e+01  2.93e-10  8.20e-11  1.73e-11  4.67e-09  2.03e-08  9.90e-01  
---------------------------------------------------------------------------------------------
Terminated with status = Solved
solve time = 13.409479ms
```

I am not a mathematician so its not so easy for me to see these things. But your explanation is very good. Thanks for that. I would maybe recommend a better API or Docs for some of these things. Maybe comparing how to translate models from CVX / Sedumi to Clarabel. I did not expect to see behind the scenes matrix augmentations etc. 

Anyway. Thanks again, Im really happy I got it working.
