### ISSUE TITLE
 QDLDLFactorisation on lower triangular matrix

### ISSUE THREAD

**Issue by Lishen1** [oxfordcontrol/Clarabel.rs#38]
is it possible, how and where change a code to make possible use  of QDLDLFactorisation with lower triangular matrix

**Comment by goulart-paul** [comment]
The QDLDL factorisation code doesn't support factorisation of a matrix whose data is in the lower triangular part.   This would require a complete rewrite of the factorisation code.

It would be better to just transpose the data prior to passing it to the factorisation module.    Note that if your data is coming from some external source, then putting the data into upper triangular form but in compressed sparse *row* format will give you  sparse matrix data that is equivalent to what you want.

**Comment by Lishen1** [comment]
thanks. i have CSC from external source but for lower part. I tried CscMatrix .t() but have no idea how to convert algebra::Adjoint to CscMatrix

**Comment by goulart-paul** [comment]
Using the `.t()` method doesn't actually transpose the data, it just marks the matrix to be treated as its transpose for things like multiplication.

There is no utility at present that forces transposition of the data itself, although it's easy enough to do.   Perhaps make a separate issue requesting such a utility?

What is your use case here - are you using the QDLDL rust code directly instead of as part of the optimisation package?

**Comment by goulart-paul** [comment]
Fixed in #46 and merged to develop.   Will appear in next minor release.
