### ISSUE TITLE
feature request - API to solve multiple times with different data

### ISSUE THREAD

**Issue by ghorn** [oxfordcontrol/Clarabel.rs#59]
I'm interested in solving a sequence of problems with the same structure for online control, and I wasn't able to find documentation on this. Is it intended that `solve` can be called multiple times on the same solver, while updating problem data between each call?

I'm interested:
* If it's possible to avoid allocation after the solver is created
* If two calls to solve will give slightly different results due to re-use of x or s
* If any of  {P, q, A, b} are more expensive or cheap to update, due to avoiding re-factorization

**Comment by goulart-paul** [comment]
It should be possible to do this with the solver in principle, and we have most (all?) of the necessary internal machinery for it.   There are no user-facing methods implemented in the solver to support it yet though.   In particular:

> If it's possible to avoid allocation after the solver is created

This is possible and would be allocation-free provided that the sparsity structure of the P and A matrices did not change.

> If two calls to solve will give slightly different results due to re-use of x or s

The solver uses an interior point method, and those are generally harder to warm start with iterates that are nearly optimal (e.g. from a similar problem) since the iterates will not be well centered.   If we implemented support for solver re-use it is likely that we would do so initially by just forcing the solver to start over from its default starting point.   You would therefore benefit from memory reuse, but not from warm starting.   

If you want to do this, maybe better to use a first order solver like SCS or OSQP.

> If any of {P, q, A, b} are more expensive or cheap to update, due to avoiding re-factorization

It wouldn't make much difference which you updated provided that you don't change the sparsity pattern of the matrices.   The reason is that an interior point solver has to re-factor its KKT matrix at every iteration anyway, so there is no harm in updating the matrix-valued problem data.   This is unlike the situation with a first order method, where some matrix formed from P and A is factored only one time.   In that case changing (P,A) requires more work than changing (q,b).

If you keep this open for now we will take it as a feature request.

**Comment by ghorn** [comment]
Thank you for accepting this, and for all the information. Sounds reasonably straightforward.

I do agree that warm-starting is not appropriate. I think that explicitly re-initializing x and s is important mainly for determinism, and if people want to mess around with warm-starting that would be a second-class interface

**Comment by ghorn** [comment]
Could you please outline what would need to be done to implement this?

**Comment by ghorn** [comment]
I'm trying to figure out if this is something I might be capable of, being completely new to rust. it looks like one would have to:

1. In DefaultProblemData, separate construction from a new initialization method that would run compute normq/normb, etc
2. add some APIs to DefaultProblemData to update P/q/A/b and mark DefaultProblemData in need of re-initialization. Expose those update APIs through IPSolver
3. In IPSolver at the beginning of solve, re-initialize DefaultProblemData if it has been updated

For testing, maybe add a way to solve twice and check that results are identical. Maybe shim this into `solve()` so that the examples and unit tests automatically check this property.

Does this sound right? I'm worried it's more complicated that that - DefaultSolver looks like it has a lot of members that might need construction separated from initialization like presolver, cones, etc

**Comment by goulart-paul** [comment]
All necessary memory is allocated by the problem constructor, so there is no need to separate allocation from the data initialisation I think.   This is assuming that you don't want to change the sparsity pattern of A or P.

I think what would be required is just a collection of methods that would allow overwriting of b, q, A and/or P, in whole or in part.   The matrices A and P are in CSC format, so you would either need to provide a completely updated set of values, or a subset of values and then a set of indices indicating where those values should go.   In the case of P, it would need to be the upper triangular part.   OSQP provides a similar set of APIs, so maybe some inspiration could be found there.

The matrix data would then need to go to three places : 

1) the "data" structure in the solver that holds scaled copies if the user defined data.   When overwriting this it would be necessary to apply the equilibration matrices to it, since the internal copy is a scaled version of the user data.   As an aside, I think it would be hard to allow for re-equilibration of the data in a numerically stable way, but I think that is not necessary anyway.  

2) the modified values would then need to be placed appropriately into the KKT matrix that was allocated during initialization.   Note that there is a data structure in the KKTSolver that provides indices indicating where values from the "A" and "P" matrices should go in the larger KKT matrix.

3) modified values then also need to be placed into the permuted copy of the KKT matrix that is held inside the qdldl factorisation object, since the linear solver applies an AMD permutation to the KKT matrix before factoring.

You would then also need to update various norms, i.e. normq, normb etc.   I also agree that having some unit tests that exercise all of these would be important.

Finally, note that we wouldn't want to merge any implementation of the above until it came with both Rust and Julia implementations and matching tests, since we're keen to keep those in sync for the foreseeable future.

I think this is a good feature request and would be happy to work on it myself, but I am very unlikely to have time to do that for the next month at least due to teaching commitments.

**Comment by ghorn** [comment]
I’m checking in on this feature request. I’m trying to gauge if it’s likely you’d have time and interest to implement it any time soon. I’m blocked on this for using the solver in a real time context. Thank you.

**Comment by goulart-paul** [comment]
I think it would be a nice feature to have, and probably essential for control applications.   We are still in the middle of academic term here though, so best case it will be implemented by end of the year.

**Comment by goulart-paul** [comment]
Working (?) rust implementation in #63.   Still needs some cleanup and FFI wrappers, which I will work on next.   There is a also a matching Julia implementation in a branch on our corresponding julia repo.

For `P` or `A` updates, it takes as input either 1) a complete CSC matrix or 2) a complete vector of values to overwrite matrix nonzeros.   For `q` and `b` it likewise accepts only a complete vector update.   

I have written it in such a way that the interface should extend easily to partial matrix or vector updates though, i.e. if you only want to overwrite a subset of entries.   This is a little bit fiddly to implement internally due to data scaling requirements, so leaving that for later on.

NB: it is necessary to disable the presolver for this to work, since otherwise the internal `P` or `A` structure may not match what the user provided, e.g. if constraint rows with infinite bounds are eliminated.

**Comment by ghorn** [comment]
Amazing! Thank you so much, this really helps us out! I'm excited to integrate it! A couple questions:

1. **Determinism**: I'm reading through [the new unit tests](https://github.com/oxfordcontrol/Clarabel.rs/pull/63/files#diff-48d55971ad810fd4f455cf7a4830d5f4ef3b20c8211c71846aec56f712874f01) to understand the properties of updates. It looks like there is some state that affects subsequent solutions
![image](https://github.com/oxfordcontrol/Clarabel.rs/assets/375331/bb530a28-40ee-4c8a-bd22-bc0b3c69198a)
Am I reading right that there is a difference between a fresh solve vs a solve with updated P. Can you comment on that?

2. **Presolver**: Besides eliminating unbounded constraint rows, does the presolver have significant effect on accuracy/robustness/performance? If the presolver is making things significantly better, it would be useful to have an interface or a solver option where the presolver can be used if we guarantee that all inequality bounds are finite. What are the options here? What would be a failure mode if an unbounded inequality were accidentally introduced in this mode?

3. **Presolver**: Is it the user's responsibility to set `presolve_enable = false`? If I leave it `true` then am I testing the proposed interface in (2.)?

Thank you again, I know you're busy.

**Comment by goulart-paul** [comment]
1.
I guess you are asking because of the relativly loose tolerance on the assertion.   I confess that this is just copy-paste and the solutions should be identical (caveat below). 

I think if you update vs make a completely fresh solver object, the solution should be the same to machine precision.   I say that (rather than "exactly the same"), because for the `q` and `b` partial updates it is necessary to unscale the vectors to compute new values of the unscaled norms of those vectors.    Possibly you get a small `eps` difference in results there vs just computing the norms directly on unscaled values.   This point is really in the weeds though.

2. 
The presolver just removes linear constraints with infinite bounds.   Keeping such constraints in place, or really any constraints with really extreme bounds, tends to make the linear solve step in the KKT conditions misbehave since those terms will appear on the RHS.    Net result is flaky convergence behaviour and termination checking usually.

If you want to selectively enable / disable constraints, maybe better to try zero-ing the corresponding row of `A` rather than setting infinite bounds.

3.
Yes, you will need to do this yourself.   The reason is that you would be trying to update the problem with data represented internally that is of a different dimension than what you originally provided, and there is no feedback from the solver to the user about which constraints were eliminated, or how many.    It might be possible to more carefully overwrite internal values with user data even when presolve is enabled, but the implementation would be more complicated.   I also didn't want to do that because we will eventually start upgrading to a proper presolve step.

Note that at present when calling from C/C++ you will produce a panic / hard error if `presolve_enable` is `true`.   This is easy to fix though, since internally in the Rust code it actually returns a more user friendly Error type.    In C++ we should probably throw something instead.   In C we could perhaps return some integer error code.   Open to suggestions here.

**Comment by ghorn** [comment]
Thank you, that all makes sense. It would be interesting to change the full-update unit test to an exact equality, to verify your theory about the only source of nondeterminism being partial updates.

Good tip about zeroing `A` instead of bounds. That's pretty forgiving actually.

I don't see any problems from the interface side. Obviously you don't want to run into `panic` in unexpected places, but it's something you find the first time you try to use the feature so it's not a risk of a lurking error. I'm unclear if the panic comes from `update` or from `solve`. If it comes from `solve` you could just add a new `Status` code and return it immediately. If it's from `update` then returning a new enum would be pretty easy. Like I said, not a big deal

**Comment by goulart-paul** [comment]
This is now available in release v0.7.0.
