### ISSUE TITLE
Increasing float precision

### ISSUE THREAD

**Issue by matzhaugen** [oxfordcontrol/Clarabel.rs#95]
Hey, 
I was wondering if there is a possibility to recompile Clarabel with increased floating point precision for increased overall precision for special problems that have such requirements. If I were to do it myself would there be anything I need to know about?
Thanks~
Matz

**Comment by goulart-paul** [comment]
It is possible, but not tested much beyond `f32`.   The reason is mostly that there is no obvious best choice of an extended precision type for us to choice.   There are several crates that provide such types, but none that is both widely used and supported on all platforms (at least last I checked).    There are some Rust RFCs for adding `f128` and `f256` types, so I was vaguely hoping that those would appear before somebody asked this question.

I think (?) that all that would be required is that the type should implement all of the traits from `num_traits` required by `CoreFloatT` : see [here](https://github.com/oxfordcontrol/Clarabel.rs/blob/77a61b5afc90a12789871650c3e12d5d956cea96/src/algebra/floats.rs#L13) for details.    You would also need to implement the `AsFloatT` trait defined [here](https://github.com/oxfordcontrol/Clarabel.rs/blob/77a61b5afc90a12789871650c3e12d5d956cea96/src/algebra/floats.rs#L83) for the type.

Two caveats : 1) if you want to get the new type to work through our Python interface to the solver, then considerably more work would be required, and 2) the above will enable solution of all problem types except for those that use the positive semidefinite cone constraint type.   Problems with PSD cones currently require BLAS, which is only available for f32 and f64.   It would be possible to get around this by implementing the required functionality (SVD, eigen-decomposition and Cholesky) using a crate that supports your preferred type, but that would again be quite a bit of extra work.

Do you have a particular type in mind that you want to use here?

**Comment by matzhaugen** [comment]
Thanks for this response. 

The type I was tentatively thinking of was f128, but if the code is currently in f32 and it would be easier to implement f64 then I think it'd be a big step to implement that first. I wasn't sure if the code supported f32 or f64 in its current form since I see both types being used in the code base (at a very cursory glance). 

Thanks

**Comment by goulart-paul** [comment]
The code is generically typed, so supports both f32 and f64.   It is written mostly with `f64` in mind though, in the sense that all of the default parameters are chosen to make sense for `f64`.   The Python interface is also only compiled with `f64`.

Supporting `f128` would also be possible at present though, even before official rust support for a native `f128` type is available.   It would just entail adding our own type from some third-party crate and then implementing some basic traits for that type.

As an aside, note that the Julia implementation of this solver works with any floating point type already.

**Comment by goulart-paul** [comment]
I am going to close this for now, since we are not actively working on extending support to any 3rd party crate for higher precision support.  Happy to revisit if there is demand though, otherwise we wait for the Rust `f128` type to appear.
